# Usar una imagen de Node.js
FROM node:18-slim

# Instalar dependencias necesarias para Puppeteer
RUN apt-get update && apt-get install -y \
    gconf-service \
    libgbm-dev \
    libasound2 \
    libatk1.0-0 \
    libcairo2 \
    libcups2 \
    libfontconfig1 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libxss1 \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Crear directorio de la aplicación
WORKDIR /usr/src/app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias (añadiendo explícitamente axios)
RUN npm install
RUN npm install axios --save

# Copiar el código fuente
COPY . .

# Exponer el puerto
EXPOSE 3000

# Crear directorio para los datos de sesión
RUN mkdir -p ./.wwebjs_auth

# Comando para iniciar la aplicación
CMD ["node", "index.js"]